import localforage from 'localforage';
import { defineStore } from 'pinia';

interface StyleState {
    isShowSection: boolean;
    selectedFont: string;
    fontSize: number;
    latterSpacing: number;
    lineHeight: number;
    bgImage: string;
    bgImageOpacity: number;
    contentWidth: number;
    fontList: string[];
}
export const useStyleStore = defineStore({
    id: 'style',
    state: (): StyleState => ({
        isShowSection: true,
        selectedFont: '微软雅黑',
        fontSize: 20,
        contentWidth: 65,
        latterSpacing: 1,
        lineHeight: 1.8,
        bgImage:
            'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg',
        bgImageOpacity: 0.16,
        fontList: [
            'Aaron Script',
            'Agency FB',
            'Alef',
            'Algerian',
            'Amiri',
            'Amiri Quran',
            'Anonymous Pro for Powerline',
            'A-OTF Jun Pro 501',
            'A-OTF Kyoukasho ICA Pro',
            'Arial',
            'Arial Rounded MT',
            'Arial Unicode MS',
            'Arimo for Powerline',
            'Bahnschrift',
            'Barlow',
            'Barrio',
            'Baskerville Old Face',
            'Bauhaus 93',
            'Beautiful ES',
            'Bell MT',
            'Berlin Sans FB',
            'Bernard MT',
            'BIZ UDGothic',
            'BIZ UDMincho',
            'BIZ UDPGothic',
            'BIZ UDPMincho',
            'Blackadder ITC',
            '本墨字造贝圆',
            'Bodoni Bd BT',
            'Bodoni Bk BT',
            'Bodoni MT',
            'Bodoni MT Poster',
            'Book Antiqua',
            'Bookman Old Style',
            'Bradley Hand ITC',
            'Britannic',
            'Broadway',
            'Brush Script MT',
            'Bubblegum Sans',
            'Cabin Sketch',
            'Caladea',
            'Calibri',
            'Californian FB',
            'Calisto MT',
            'Cambria',
            'Cambria Math',
            'Candara',
            'Carlito',
            'Cascadia Code',
            'Cascadia Mono',
            'Castellar',
            'Centaur',
            'CentSchbkCyrill BT',
            'Century',
            'Century Gothic',
            'Century Schoolbook',
            'Century725 Cn BT',
            'Century751 BT',
            'Century751 No2 BT',
            'Century751 SeBd BT',
            'Chiller',
            'Clarendon Blk BT',
            'Clarendon BT',
            'Clarendon Lt BT',
            'Colonna MT',
            'Comfortaa',
            'Comic Sans MS',
            'Consolas',
            'Constantia',
            'Cooper',
            'Copperplate Gothic',
            'Corbel',
            'Courier New',
            'Courier Prime',
            'Cousine for Powerline',
            'Curlz MT',
            'David CLM',
            'David CLM BoldItalic',
            'David CLM MediumItalic',
            'David Libre',
            'DejaVu Math TeX Gyre',
            'DejaVu Sans',
            'DejaVu Sans Mono',
            'DejaVu Sans Mono for Powerline',
            'DejaVu Serif',
            'Delius',
            '等线',
            'DeVinne Txt BT',
            'DFGothic-EB',
            '华康手札体W7-A',
            'DFKaiSho-SB',
            'DFMincho-SU',
            'DFMincho-UB',
            'DFMincho-W5',
            'DFPOP1-W9',
            'Dosis',
            'Droid Sans Mono Dotted for Powerline',
            'Droid Sans Mono for Powerline',
            'Droid Sans Mono Slashed',
            'Droid Sans Mono Slashed for Powerline',
            'EarMasterJazz',
            'EarMasterJazzText',
            'Ebrima',
            'Edwardian Script ITC',
            'Elephant',
            'Embassy BT',
            'EmojiOne Color',
            'Engravers MT',
            'EngraversGothic BT',
            'Eras ITC',
            'Exotc350 Bd BT',
            'Exotc350 DmBd BT',
            '仿宋',
            'Felix Titling',
            'Fira Code',
            'Fira Code Retina',
            'Fira Mono for Powerline',
            'Footlight MT',
            'Forte',
            'FOT-BabyPop Std',
            'FOT-ComicReggae Std',
            'FOT-Humming ProN E',
            'FOT-Humming Std',
            'FOT-NewRodin ProN',
            'FOT-Pearl Std',
            'Frank Ruehl CLM',
            'Frank Ruehl CLM BoldOblique',
            'Frank Ruehl CLM MediumOblique',
            'Frank Ruhl Hofshi',
            'Franklin Gothic',
            'Franklin Gothic Book',
            'Fredericka the Great',
            'Fredoka One',
            'Freehand521 BT',
            'Freestyle Script',
            'French Script MT',
            'Futura Bk BT',
            'Futura Md BT',
            '方正报宋简体',
            '方正北魏楷书简体',
            '方正北魏楷书繁体',
            '方正超粗黑繁体',
            '方正辞源宋体',
            '方正粗黑宋简繁',
            '方正粗黑宋简体',
            '方正大黑简体',
            '方正仿宋_GBK',
            '方正FW珍珠体 简繁',
            '方正剪纸_GBK',
            '方正楷体_GBK',
            '方正兰亭粗黑_GBK',
            '方正兰亭圆_GBK_粗',
            '方正兰亭圆_GBK_中粗',
            '方正兰亭圆_GBK_中',
            '方正兰亭圆_GBK_大',
            '方正兰亭圆_GBK_纤',
            '方正兰亭圆_GBK_特',
            '方正兰亭圆_GBK_细',
            '方正兰亭圆_GBK_准',
            '方正兰亭圆_GBK',
            '方正兰亭圆简体_粗',
            '方正兰亭圆简体_中粗',
            '方正兰亭圆简体_中',
            '方正兰亭圆简体_大',
            '方正兰亭圆简体_纤',
            '方正兰亭圆简体_特',
            '方正兰亭圆简体_细',
            '方正兰亭圆简体_准',
            '方正兰亭圆简体',
            '方正少儿_GBK',
            '方正诗甜宋 简繁',
            '方正舒体',
            '方正姚体',
            '方正粗雅宋_GBK',
            '方正特雅宋_GBK',
            '方正悠黑_GBK 513B',
            '方正悠宋+ GBK 509R',
            '方正正粗黑_GBK',
            '方正筑紫明朝宋 简繁',
            'Gabriola',
            'Gadugi',
            'Garamond',
            'Gentium Basic',
            'Gentium Book Basic',
            'Geometr212 BkCn BT',
            'Geometr415 Blk BT',
            'Geometr706 BlkCn BT',
            'Georgia',
            'GeoSlab703 Md BT',
            'GeoSlab703 MdCn BT',
            'Gigi',
            'Gill Sans',
            'Gill Sans MT',
            'Global Monospace',
            'Global Sans Serif',
            'Global Serif',
            'Global User Interface',
            'Gloucester MT',
            'Go Mono for Powerline',
            'Goudy Old Style',
            'Goudy Stout',
            'Guitar Pro 5',
            'Hack',
            'Hack BoldOblique',
            'Hack Nerd Font',
            'Hack NF',
            'Haettenschweiler',
            'hakuyoxingshu7000',
            'Harlow Solid',
            'Harrington',
            'High Tower Text',
            'Hiragino Mincho StdN',
            'HoloLens MDL2 Assets',
            'Humanst521 BT',
            'Humanst521 Lt BT',
            'Humnst777 Blk BT',
            'Humnst777 BlkCn BT',
            'Humnst777 BT',
            'Humnst777 Cn BT',
            'Humnst777 Lt BT',
            'HYQiHei 40S',
            '汉仪晓波暖宋',
            'IBM 3270',
            'IBM 3270 Semi',
            'icomoon',
            'Impact',
            'Imprint MT Shadow',
            'Inconsolata for Powerline',
            'Inconsolata for Powerline BoldForPowerline',
            'Inconsolata-dz for Powerline',
            'Inconsolata-g for Powerline',
            'Informal Roman',
            'Ink Free',
            '印品篆遇简',
            'Javanese Text',
            'Jokerman',
            'Juice ITC',
            'Julius Sans One',
            'KacstBook',
            'KacstOffice',
            '楷体',
            'Kaufmann BT',
            'Kristen ITC',
            'Kunstler Script',
            'Leelawadee UI',
            'Liberation Mono',
            'Liberation Mono for Powerline',
            'Liberation Sans',
            'Liberation Serif',
            'Linux Biolinum G',
            'Linux Libertine Display G',
            'Linux Libertine G',
            '隶书',
            'Lucida Bright',
            'Lucida Calligraphy',
            'Lucida Console',
            'Lucida Fax',
            'Lucida Handwriting',
            'Lucida Sans',
            'Lucida Sans Typewriter',
            'Lucida Sans Unicode',
            'Magneto',
            'Maiandra GD',
            'Malgun Gothic',
            'Marlett',
            'Matura MT Script Capitals',
            'Megrim',
            'Meiryo',
            'Meiryo UI',
            'Meslo LG L DZ for Powerline',
            'Meslo LG L for Powerline',
            'Meslo LG M DZ for Powerline',
            'Meslo LG M for Powerline',
            'Meslo LG S DZ for Powerline',
            'Meslo LG S for Powerline',
            'MesloLGL Nerd Font',
            'MesloLGL Nerd Font Mono',
            'MesloLGL NF',
            'MesloLGL NFM',
            'MesloLGLDZ Nerd Font',
            'MesloLGLDZ Nerd Font Mono',
            'MesloLGLDZ NF',
            'MesloLGLDZ NFM',
            'MesloLGM Nerd Font',
            'MesloLGM Nerd Font Mono',
            'MesloLGM NF',
            'MesloLGM NFM',
            'MesloLGMDZ Nerd Font',
            'MesloLGMDZ Nerd Font Mono',
            'MesloLGMDZ NF',
            'MesloLGMDZ NFM',
            'MesloLGS Nerd Font',
            'MesloLGS Nerd Font Mono',
            'MesloLGS NF',
            'MesloLGS NFM',
            'MesloLGSDZ Nerd Font',
            'MesloLGSDZ Nerd Font Mono',
            'MesloLGSDZ NF',
            'MesloLGSDZ NFM',
            'MHGReithic T HK',
            'Microsoft Himalaya',
            'Microsoft JhengHei',
            'Microsoft JhengHei UI',
            'Microsoft New Tai Lue',
            'Microsoft PhagsPa',
            'Microsoft Sans Serif',
            'Microsoft Tai Le',
            '微软雅黑',
            'Microsoft YaHei UI',
            'Microsoft Yi Baiti',
            'MingLiU_HKSCS-ExtB',
            'MingLiU-ExtB',
            'Miriam CLM',
            'Miriam Libre',
            'Miriam Mono CLM',
            'Miriam Mono CLM BoldOblique',
            'Mistral',
            'Modern No. 20',
            'Mongolian Baiti',
            'monofur for Powerline',
            'Monoton',
            'Monotype Corsiva',
            'MS Gothic',
            'MS Mincho',
            'MS PGothic',
            'MS PMincho',
            'MS UI Gothic',
            'MT Extra',
            'MV Boli',
            'Myanmar Text',
            'MYoyo HK',
            'MYoyo PRC',
            'Nachlieli CLM',
            'Nachlieli CLM BoldOblique',
            'Nachlieli CLM LightOblique',
            'Nanum Pen',
            'News701 BT',
            'News706 BT',
            'NewsGoth BT',
            'NewsGoth Cn BT',
            'NewsGoth Lt BT',
            'Niagara Engraved',
            'Niagara Solid',
            'Nirmala UI',
            'Noto Kufi Arabic',
            'Noto Mono',
            'Noto Mono for Powerline',
            'Noto Naskh Arabic',
            'Noto Naskh Arabic UI',
            'Noto Sans',
            'Noto Sans Arabic',
            'Noto Sans Arabic UI',
            'Noto Sans Armenian',
            'Noto Sans Georgian',
            'Noto Sans Hebrew',
            'Noto Sans Lao',
            'Noto Sans Lisu',
            'Noto Serif',
            'Noto Serif Armenian',
            'Noto Serif Georgian',
            'Noto Serif Hebrew',
            'Noto Serif Lao',
            'NovaMono for Powerline',
            '新宋体',
            'NumberOnly',
            'OCR A',
            'OCR-A BT',
            'OCR-B 10 BT',
            'Old English Text MT',
            'Onyx',
            'OpenSymbol',
            'Palace Script MT',
            'Palatino Linotype',
            'Pangolin',
            'Papyrus',
            'Parchment',
            'Perpetua',
            'Perpetua Titling MT',
            'Playbill',
            'PMingLiU-ExtB',
            'Poor Richard',
            'Primus',
            'Pristina',
            'ProFont for Powerline',
            'Rage',
            'Raleway',
            'Ravie',
            'Reem Kufi',
            'Roboto Mono for Powerline',
            'Roboto Mono Light for Powerline',
            'Roboto Mono Medium for Powerline',
            'Roboto Mono Thin for Powerline',
            'Rockwell',
            'Rubik',
            'Schadow BT',
            'Scheherazade',
            'Script MT',
            'Segoe MDL2 Assets',
            'Segoe Print',
            'Segoe Script',
            'Segoe UI',
            'Segoe UI Emoji',
            'Segoe UI Historic',
            'Segoe UI Symbol',
            'Shadows Into',
            'Showcard Gothic',
            '黑体',
            '宋体',
            'SimSun-ExtB',
            'Sitka Banner',
            'Sitka Display',
            'Sitka Heading',
            'Sitka Small',
            'Sitka Subheading',
            'Sitka Text',
            'Snap ITC',
            'Source Code Pro',
            'Source Code Pro for Powerline',
            '思源黑体 CN',
            'Source Han Sans JP',
            '思源宋体 CN',
            'Source Han Serif JP',
            'Source Sans Pro',
            'Source Serif Pro',
            'Space Mono',
            'Space Mono for Powerline',
            'Square721 BT',
            'Square721 Cn BT',
            '华文彩云',
            'Stencil',
            '华文仿宋',
            '华文琥珀',
            '华文楷体',
            '华文隶书',
            '华文宋体',
            '华文细黑',
            '华文行楷',
            '华文新魏',
            '华文中宋',
            'Swis721 Blk BT',
            'Swis721 BlkCn BT',
            'Swis721 BT',
            'Swis721 Cn BT',
            'Swis721 Hv BT',
            'Swis721 Lt BT',
            'Swis721 LtEx BT',
            'Swis721 WGL4 BT',
            'Sylfaen',
            'Symbol',
            'Symbol Neu for Powerline',
            'Tahoma',
            'Tempus Sans ITC',
            '腾祥嘉丽大圆GB18030',
            'Tensentype QinYuanJ W3',
            '腾祥伯当行楷GB18030',
            'Times New Roman',
            'Tinos for Powerline',
            'Trebuchet MS',
            'Tw Cen MT',
            'TypoUpright BT',
            'Ubuntu Mono derivative Powerline',
            'UD Digi Kyokasho N-B',
            'UD Digi Kyokasho NK-B',
            'UD Digi Kyokasho NK-R',
            'UD Digi Kyokasho NP-B',
            'UD Digi Kyokasho NP-R',
            'UD Digi Kyokasho N-R',
            'Vast Shadow',
            'Verdana',
            'Viner Hand ITC',
            'Virtuoso',
            'Vivaldi',
            'Vladimir Script',
            'Webdings',
            'Wide Latin',
            'Wingdings',
            'Wingdings 2',
            'Wingdings 3',
            '幼圆',
            'Yu Gothic',
            'Yu Gothic UI',
            'Yu Mincho',
            'Zilla Slab',
            'ZWAdobeF',
            '绿木屐JXP行楷',
            '文鼎行楷碑體',
            '叶根友毛笔行书2.0版',
        ],
    }),
    getters: {},
    actions: {
        resetStyle() {
            this.selectedFont = 'system';
            this.fontSize = 20;
            this.bgImage = '';
            this.lineHeight = 1.8;
            this.latterSpacing = 0;
            this.contentWidth = 65;
        },
        save() {
            const styleData = {
                isShowSection: this.isShowSection,
                selectedFont: this.selectedFont,
                fontSize: this.fontSize,
                bgImage: this.bgImage,
                bgImageOpacity: this.bgImageOpacity,
                lineHeight: this.lineHeight,
                latterSpacing: this.latterSpacing,
                contentWidth: this.contentWidth,
            };
            localforage.setItem('styleSetting', JSON.stringify(styleData));
        },
        restore() {
            localforage.getItem('styleSetting').then((styleData) => {
                if (styleData) {
                    const data = JSON.parse(styleData as string);
                    this.isShowSection = data.isShowSection;
                    this.selectedFont = data.selectedFont;
                    this.fontSize = data.fontSize;
                    this.bgImage = data.bgImage;
                    this.bgImageOpacity = data.bgImageOpacity;
                    this.lineHeight = data.lineHeight;
                    this.latterSpacing = data.latterSpacing;
                    this.contentWidth = data.contentWidth;
                }
            });
        },
    },
});
